apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
        ref:
          branch: main
    commit:
      author:
        email: hoang171220001@gmail.com
        name: fluxbot
      messageTemplate: 'update image'
    push:
      branch: main
  interval: 1m0s
  update:
    path: ./default
    strategy: Setters